name: Docker Image CI (Docker Hub)

on:
  workflow_dispatch: 
  push:
    branches:  
      - "development"

jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository on linux machine
        uses: actions/checkout@v4
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      - name: Extract version from pom.xml
        id: extract_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Login Docker Hub
        id: docker-hub
        env:
          dockerImageName: poc-neo4j-service
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $username -p $password
      - name: Build Docker Image
        id: build-docker-image
        run: docker build -t $dockerImageName:1.0.0 .
      - name: Post Docker Image to Docker Hub
        id: push-docker-image
        run: docker push $dockerImageName:$GITHUB_ENV
